# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GimmeSnowflakeCreds < Formula
  desc "Okta > OAuth > Snowflake > Creds"
  homepage "https://github.com/HGInsights/gimme-snowflake-creds"
  version "0.2.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.2.3/gimme-snowflake-creds_0.2.3_darwin_amd64.tar.gz"
      sha256 "c4ed72406b650893a3b021f717a6f986e08ea707e00675be32fd4bd148a6d160"
    end
    if Hardware::CPU.arm?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.2.3/gimme-snowflake-creds_0.2.3_darwin_arm64.tar.gz"
      sha256 "68e29fd8985f5460c21fd10c9127e86f9a0f1acaea7555aef053a0526a7a24d6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.2.3/gimme-snowflake-creds_0.2.3_linux_amd64.tar.gz"
      sha256 "8e1d8d7e0987605393c52d4390662cf4296056ecc30adbd035cdf7b7ca0f5f6f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.2.3/gimme-snowflake-creds_0.2.3_linux_arm64.tar.gz"
      sha256 "6738e950909936be9e69786a005bafdfccfd54644f0dd53fc2adb87ed8b826b2"
    end
  end

  def install
    bin.install "gimme-snowflake-creds"
  end
end
