name: CI

on:
  pull_request:
  push:
    branches:
    - main

env:
  GO_VERSION: '^1.16.3'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${GO_VERSION}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check formatting
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi 

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${GO_VERSION}
        
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    